name: reservaiq-cpu
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - numpy==1.26.4
      - pandas==2.2.3
      - scikit-learn==1.3.2
      - joblib==1.6.0
